### ISSUE TITLE
[build] why configure jar task even if it is marked as disabled

### ISSUE THREAD

**Issue by anatawa12** [yuitosaito/Image-Resource-Mod#4]
https://github.com/yuitosaito/Image-Resource-Mod/blob/e93fe98d7defe3485df3a61dcff3730ceddee856/build.gradle#L101-L109

Here, the configuration of the jar task seems to create a fat jar but the jar task is disabled. This means the jar task always skipped and the configuration for it always be ignored. Why do you configure the jar task even if it is marked as disabled?

**Comment by noyciy7037** [comment]
https://forums.minecraftforge.net/topic/37528-using-external-libraries-in-my-mod/?tab=comments#comment-200300
I've referred to this, so I'm not sure about the details, but I think it's okay to delete it.

**Comment by anatawa12** [comment]
It seems you configured to create a fat jar using a plugin and jar task and configuration for jar task is ignored by 'jar.enabled = false ' so please choose which way will you use and modify and commit.

**Comment by noyciy7037** [comment]
Removed the jar task configuration.

**Comment by anatawa12** [comment]
OK, I checked this problem is fixed in aecfa9489e5b634359d227379ec71cc68f84f03c but I think you should use Pull Request linked to this issue to close this issue automatically and to make it easy to know when is this problem fixed. see [Github Documentation](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to know about linked pull requests to issues.
